### ISSUE TITLE
Look into libact meta-learner

### ISSUE THREAD

**Issue by SeanLF** [SeanLF/CSI4900#7]

**Comment by markkasun** [comment]
Fixed the error that was popping up. A parameter is missing in the documentation on libact. It needs a parameter T described below. I set it to 1000 for now. Also removed HintSVM since it has it's own bug. The bug is fixed but now we'll need to look into which learning strategies the meta-learner will use, and this relates to fixing the bug in issue #3.

```
T : integer
    Query budget, the maximal number of queries to be made.
```
